# Generated by Django 5.2.7 on 2025-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(max_length=500, upload_to='downloads/'),
        ),
    ]
