# Generated by Django 5.2.7 on 2025-10-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='gallery/'),
        ),
    ]
