# Generated by Django 5.2.7 on 2025-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_contact_email_department_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default='No description yet'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='departments/'),
        ),
    ]
